### ISSUE TITLE
current version is 5.0x not 3.5

### ISSUE THREAD

**Issue by kazamatzuri** [ogra1/zoom-snap#18] opened 2020-04-28 17:14 UTC
this installs the old version?

**Comment by ogra1** [comment] 2020-04-28 20:21
yup, seems the automatic build has failed ... 
https://launchpad.net/~build.snapcraft.io/+snap/8945c491a02ce87321c5fed28c171d3b/+build/929407

**Comment by ogra1** [comment] 2020-04-28 20:28
and awesomely it seems like there is a fix for this in https://github.com/ogra1/zoom-snap/pull/19 ... 
note though that even if it builds it might take a bit time to test it and weed out potential other issues caused by the version change ... 

the next build should at least succeed though and whatever comes out of it will be available in the edge channel for testing ...

**Comment by ogra1** [comment] 2020-04-29 17:07
so there were actually some other issues (launching browser windows stopped working due to some re-design on zooms side etc) that are now resolved ... 5.xx is in the stable channel now, enjoy !

**Closed by ogra1** 2020-04-29 17:07 UTC
