### ISSUE TITLE
Cannot share screen

### ISSUE THREAD

**Issue by anggapw** [ogra1/zoom-snap#42] opened 2020-07-24 03:17 UTC
Hi, i am using Fedora 32 and Gnome shell 3.36

when I want to use the share screen feature, an error message appears

"Cant not start share, we only support Wayland on GNOME with Ubuntu 17 and above, Fedora 25 and above, Debian 9 and above, CentOS 8 and above, OpenSUSE Leap 15 and above, Oracle Linux 8 and above, RHEL 8 and above, Arch Linux, AnterGos, Manjaro. If your OS is not on the list, please use x11 instead.

**Comment by ogra1** [comment] 2020-07-24 10:00
this is a duplicate of #22

**Closed by ogra1** 2020-07-24 10:00 UTC
